apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  BG_COLOR: {{ .Values.data.BG_COLOR }}
  FONT_COLOR: {{ .Values.data.FONT_COLOR }}
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}