appName: myhelmapp

namespace: default

configmap:
  name: helmappconfigmapv1.1
  data:
    CUSTOM_HEADER: "This app was deployed with helm!"

image:
  name: devopsjourney1/mywebapp
  tag: latest

data:
  BG_COLOR: '#2F5233'   # Forest green
  FONT_COLOR: '#D8F3DC' # Pale mint


